version: '3.8'
services:
  db:
    image: postgres:15
    container_name: desafio-db-restaurado
    environment:
      POSTGRES_DB: desafio_backend_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - desafiodx-pj_postgres_data:/var/lib/postgresql/data

volumes:
  desafiodx-pj_postgres_data:
    external: true
